// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DiscServers():Promise<Array<string>>;

export function GetFiles():Promise<Array<main.fileData>>;

export function ReqFile(arg1:string):Promise<string>;

export function SetClientConnection(arg1:string):Promise<boolean>;
