// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscServers() {
  return window['go']['main']['App']['DiscServers']();
}

export function GetCurrentServerDir() {
  return window['go']['main']['App']['GetCurrentServerDir']();
}

export function GetFilesFromClient() {
  return window['go']['main']['App']['GetFilesFromClient']();
}

export function GetFilesFromServer(arg1) {
  return window['go']['main']['App']['GetFilesFromServer'](arg1);
}

export function GetServerDirectory() {
  return window['go']['main']['App']['GetServerDirectory']();
}

export function ReqFile(arg1) {
  return window['go']['main']['App']['ReqFile'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetClientConnection(arg1) {
  return window['go']['main']['App']['SetClientConnection'](arg1);
}
